@base_url = http://127.0.0.1:8000

### Criação de uma série
POST {{base_url}}/ HTTP/1.1
Content-Type: application/json

{
    "titulo": "Rick and Morty",
    "descricao": "Avô e neto em altas aventuras interdimensionais",
    "ano_lancamento": 2013
}

### Obtenção de todas as séries
GET {{base_url}}/series HTTP/1.1
Accept: application/json

### Atualização da série (substitua manualmente pelo id retornado)
PUT {{base_url}}/1 HTTP/1.1
Content-Type: application/json

{
    "titulo": "Rick and Morty Updated",
    "descricao": "Novas aventuras interdimensionais",
    "ano_lancamento": 2014
}

### Deleção da série (substitua manualmente pelo id retornado)
DELETE {{base_url}}/1 HTTP/1.1
Accept: application/json